### ISSUE TITLE
README fixes

### ISSUE THREAD

**Issue by brandtam** [sanity-io/sanity-template-sveltekit-clean#1]
In the `Getting started` section on step 2 it says that you can use the 'sanity init --env' if you have the CLI installed.

This didn't work for me. When I tried the CLI it said that it was for V2 

but then asked if I wanted to continue with the V3 installation. 

I said yes and it just went ahead and created a whole new studio directory rather than just the .env file in the way that the npm package does.

Suggested Fix: Remove the line about using the CLI.

**Comment by benja** [comment]
hey! the min required version for the `--env` flag is sanity@3.9.0, if you install the latest (3.11.1) you won't have this issue anymore.
