### ISSUE TITLE
Minor error in install instructions and mismatched env variable names

### ISSUE THREAD

**Issue by ehowey** [sanity-io/sanity-template-sveltekit-clean#14]
Hello!

I just went to install this and followed the readme and ran into a couple of minor errors when getting the project setup and running. Happy to make a PR for this if it helps. The second issue is maybe a bit more nuanced, IIRC there is a reason within SvelteKit to preface env variables with PUBLIC? I might be forgetting something there but I wonder if there is a need for that prefix.

1. The command `npm create sanity@latest init --env` doesn't seem to work correctly, however `sanity init --env` does. The npm create command runs through a full install of Sanity without outputting an env variable. I think the correct command should be `npx -y sanity@latest init --env`.
2. In the SvelteKit app the environment variables it is looking for are `PUBLIC_SANITY_DATASET` and `PUBLIC_SANITY_PROJECT_ID`. When you run the `sanity init --env` command it spits out `SANITY_PROJECT_ID` and `SANITY_DATASET` with our the PUBLIC prefix.  The easiest fix for me was to just correct the environment variables themselves.

**Comment by evenwestvang** [comment]
Would be glad to accept PRs for both issues  - I'd have to defer to @stipsan on the necessity of that naming for the env vars.
