### ISSUE TITLE
CORS issues in app

### ISSUE THREAD

**Issue by jlrickert** [sanity-io/sanity-template-sveltekit-clean#19]
I followed the readme to bring up a working example on my local machine. I created content in the studio and was able to see it in the list of posts.  However, when I clicked on it I got a 500 error. Based on the readme I would expect to be able to view the content.

I did find a work around by adding http://localhost:5173 to the list of CORS origins in the sanity portal by following the doumentation at https://www.sanity.io/docs/cors.

**Comment by doommchips** [comment]
i was experiencing the same issue and your workaround worked, thank you

**Comment by rdunk** [comment]
Closing as this is expected behaviour.
