### ISSUE TITLE
No visual editing?

### ISSUE THREAD

**Issue by jssteinberg** [sanity-io/sanity-template-sveltekit-clean#29]
**Is your feature request related to a problem? Please describe.**
I couldn't see that this provides visual editing, which seem like a mess to add. Hope I'm wrong. https://www.sanity.io/docs/visual-editing

**Describe the solution you'd like**
Sanity studio visual editing.

**Describe alternatives you've considered**
This is the new way for live preview while editing in Sanity studi as far as I can see.

**Comment by rdunk** [comment]
Coming shortly in #35.

**Comment by Renkas** [comment]
This does not seem to include Overlays? Maybe that could be a next thing to add? 

Anyway thanks for the example

**Comment by rdunk** [comment]
The `@sanity/overlays` package has been deprecated. Overlays functionality is now provided by `@sanity/visual-editing`.

**Comment by Renkas** [comment]
Yes that's what I was thinking. But as there is still no SvelteKit example there I have no idea how to get started on that (I'm pretty new to Sanity)

**Comment by rdunk** [comment]
Sure thing! Hoping to get this signed off and released tomorrow.

**Comment by jssteinberg** [comment]
Great stuff! Looking forward to testing this.

**Comment by rdunk** [comment]
Merged into main! Closing, but please let us know if you run into any issues.

**Comment by jssteinberg** [comment]
Everything works nice locally. Currently I haven't been able to get "Presentation" with live updates to work when Studio is deployed to production (as subdomain at sanity.studio). The Sveltekit app is deployed at Cloudlare Pages and works, and shows up in "Presentation" but studio is not able to connect to visual editing. From console:

```
Unable to connect to visual editing. Make sure you've setup '@sanity/visual-editing' correctly
```

Before this message some of the error messages are CORS related ("same origin-policy") when studio tries to `get` from api.sanity.io.

`SANITY_STUDIO_PREVIEW_URL` in Studio's env is updated to Sveltekit-app in prod.

Another, perhaps related, question: should both app and studio preferably be deployed to same domain?

**Comment by sebbean** [comment]
same - i feel like maybe the timeout is too short? (only 3s)

being able to configure:
`MAX_TIME_TO_OVERLAYS_CONNECTION`

would be amazing

**Comment by theIbraDev** [comment]
Having the same issue. It works perfectly locally, but once it's hosted, and on 2 seperate subdomains, it stops working and i get the same error message.



> > Everything works nice locally. Currently I haven't been able to get "Presentation" with live updates to work when Studio is deployed to production (as subdomain at sanity.studio). The Sveltekit app is deployed at Cloudlare Pages and works, and shows up in "Presentation" but studio is not able to connect to visual editing. From console:
> > ```
> > Unable to connect to visual editing. Make sure you've setup '@sanity/visual-editing' correctly
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Before this message some of the error messages are CORS related ("same origin-policy") when studio tries to `get` from api.sanity.io (in Firefox, not in Chromium though).
> > `SANITY_STUDIO_PREVIEW_URL` in Studio's env is updated to Sveltekit-app in prod.
> > Another, perhaps related, question: should both app and studio preferably be deployed to same domain?
> 
> I am having a similar problem, except mine is happening during local development

**Comment by jssteinberg** [comment]
> Having the same issue. It works perfectly locally, but once it's hosted, and on 2 seperate subdomains, it stops working and i get the same error message.
> 
> Edit: My fault, somehow i didn't set SANITY_STUDIO_PREVIEW_URL, i didn't realize i was missing the [www](http://www). at the front of my domain....
> 
> > > Everything works nice locally. Currently I haven't been able to get "Presentation" with live updates to work when Studio is deployed to production (as subdomain at sanity.studio). The Sveltekit app is deployed at Cloudlare Pages and works, and shows up in "Presentation" but studio is not able to connect to visual editing. From console:
> > > ```
> > > Unable to connect to visual editing. Make sure you've setup '@sanity/visual-editing' correctly
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Before this message some of the error messages are CORS related ("same origin-policy") when studio tries to `get` from api.sanity.io (in Firefox, not in Chromium though).
> > > `SANITY_STUDIO_PREVIEW_URL` in Studio's env is updated to Sveltekit-app in prod.
> > > Another, perhaps related, question: should both app and studio preferably be deployed to same domain?
> > 
> > 
> > I am having a similar problem, except mine is happening during local development

So you got visual editing working in production?

**Comment by rdunk** [comment]
@sebbean did you manage to resolve your issues without being able to increase the timeout value? Internally we've previously discussed making that user configurable, so just looking for an indication if that's something that would be useful.

**Comment by sebbean** [comment]
@rdunk i ended up switching the whole web app over to next.js instead of nuxt

i'm now having issues with:

`Visual editing package mismatch detected!`

between the (previously existing) standalone studio package / app

and  the next.js app that doesnt have the studio mounted within it

debating if  i want to migrate the studio into next or keep them separated

and how i can lock the sanity versions together if i keep them separate

**Comment by rdunk** [comment]
@sebbean If you update your studio and app related Sanity dependencies to the latest versions you shouldn't see that error.

**Comment by theIbraDev** [comment]
> I'm currently working on a Next.js project and integrating Sanity with a presentation tool. However, I've encountered the following error:
> 
> (PresentationTool-2QKQ3IHD.js?v=d3749efe:1359 Unable to connect to visual editing. Make sure you've setup '@sanity/visual-editing' correctly)
> 
> I've thoroughly gone through the documentation related to @sanity/visual-editing, but I haven't been able to resolve the issue. Could you kindly provide guidance or point me in the right direction to fix this?

This is a sveltekit template, not next.
You might want to take a look at this:
https://www.sanity.io/guides/nextjs-app-router-live-preview
and 
 https://github.com/SimeonGriggs/sanity-nextjs-preview
