### ISSUE TITLE
postcss config file extension should be changed to .cjs

### ISSUE THREAD

**Issue by brandtam** [sanity-io/sanity-template-sveltekit-clean#3]
The `package.json` file informs us that `.js` files are interpreted as native JavaScript modules with `import` and `export` keywords. 

This causes an error when deploying the current build.

Suggested Fix: Rename `postcss.config.js` to `postcss.config.cjs`

[Reference](https://kit.svelte.dev/docs/project-structure#project-files-package-json)

**Comment by benja** [comment]
thanks! 🙌🏼
