### ISSUE TITLE
Typescript errors in latest

### ISSUE THREAD

**Issue by CallumHoward** [sanity-io/sanity-template-sveltekit-clean#40]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Typescript errors are now present on fresh setup from this template.

```sh
../node_modules/.pnpm/@sanity+visual-editing@2.1.6_@sanity+client@6.21.0_@sveltejs+kit@2.5.18_@sveltejs+vite-plugin_njwzx3qam3eyj7zkarpyrgwvd4/node_modules/@sanity/visual-editing/src/types.ts:1:33 - error TS2307: Cannot find module '@repo/channels' or its corresponding type declarations.

1 import type {ChannelsNode} from '@repo/channels'
                                  ~~~~~~~~~~~~~~~~

../node_modules/.pnpm/@sanity+visual-editing@2.1.6_@sanity+client@6.21.0_@sveltejs+kit@2.5.18_@sveltejs+vite-plugin_njwzx3qam3eyj7zkarpyrgwvd4/node_modules/@sanity/visual-editing/src/types.ts:10:8 - error TS2307: Cannot find module '@repo/visual-editing-helpers' or its corresponding type declarations.

10 } from '@repo/visual-editing-helpers'
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../node_modules/.pnpm/@sanity+visual-editing@2.1.6_@sanity+client@6.21.0_@sveltejs+kit@2.5.18_@sveltejs+vite-plugin_njwzx3qam3eyj7zkarpyrgwvd4/node_modules/@sanity/visual-editing/src/types.ts:17:8 - error TS2307: Cannot find module '@repo/visual-editing-helpers' or its corresponding type declarations.

17 } from '@repo/visual-editing-helpers'
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

1. Cone this repo
2. Install with `pnpm`
3. `cd app && npx tsc --noEmit`
4. Type errors are shown

**Expected behavior**

No type errors (excluding errors from missing .env vars)

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

* pnpm: 9.6.0
* node: v18.14.0

**Additional context**

It should be ignoring type issues that occur inside `node_modules` because of the exclude rule in the generated `.svelte-kit/tsconfig.json`, which is extended from. I tried adding it explicitly in `app/tsconfig.json` but no luck there.

**Comment by rdunk** [comment]
Hey @CallumHoward, thanks for the report. I was able to reproduce using your steps, and we've shipped a fix in the latest version of `@sanity/visual-editing` which this template is now using. Can you confirm if this fixes the issue for you?
