### ISSUE TITLE
Lint errors re svelte files on fresh install

### ISSUE THREAD

**Issue by webel** [sanity-io/sanity-template-sveltekit-clean#42]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

On a fresh install of this template I receive lint errors regarding svelte files not being used and then not being defined.

**To Reproduce**

1. Clone this repo
2. Open src/routes/+page.svelte

**Expected behavior**

I expect the tsconfig/eslint, whichever it is, to be configured as to not throw errors.

**Screenshots**
![Screenshot 2024-08-13 at 14 13 27](https://github.com/user-attachments/assets/629d90b0-6d87-4386-8689-6a1ead11a4d0)

**Which versions of Sanity are you using?**
@sanity/cli (global)     3.53.0 (up to date)
@sanity/image-url         1.0.2 (up to date)
@sanity/svelte-loader   1.11.35 (latest: 1.11.36)
@sanity/types            3.52.4 (latest: 3.53.0)
@sanity/visual-editing    2.1.8 (latest: 2.1.9)

**What operating system are you using?**
Mac, 14.5 (23F79)

**Which versions of Node.js / npm are you running?**
npm -v && node -v

**Comment by rdunk** [comment]
I'm not able to reproduce this, would you be able to provide more specific reproduction steps? Following the steps you've provided will result in errors as dependencies will not have been installed.

**Comment by webel** [comment]
Right, sorry, these are the exhaustive steps;

1. Clone this repo
2. pnpm install in root
3. Move files from routes/* to routes/example/*
4. Open src/routes/example/+page.svelte

I solved the issue by using `eslint-plugin-svelte` instead of `eslint-plugin-svelte3` as the former is the recommended way to go; https://github.com/sveltejs/eslint-plugin-svelte. I could submit a PR making the changes if that's of interest (granted I understand I probably stumbled on some strange edge case triggered by my editor or something).
